### ISSUE TITLE
Indexing exported google contacts fails

### ISSUE THREAD

**Issue by j605** [pimutils/mates.rs#24]
Google contacts allows you to export all contacts in a single vcf file. But this does not work with `mates` which cannot import the whole file. I had to resort to this since `vdirsyncer` was not able to sync all my contacts. It just outputs:
```sh
Error while reading /home/jagan/.contacts/contacts.vcf: Error while parsing contact: Trailing data: `BEGIN:VCARD
---snipped---
the whole file after the first VCARD
---continued---
END:VCARD
`
Several errors happened while generating the index
```

**Comment by untitaker** [comment]
You can export the file, then sync it as `singlefile` using vdirsyncer to a `filesystem` folder.

mates itself does not deal with multiple vcards in one file. It would make it very slow
