### ISSUE TITLE
Unable to edit contact after adding from mutt

### ISSUE THREAD

**Issue by rbnvrw** [pimutils/mates.rs#26]
Thank you very much for writing mates!

I was wondering how to edit a contact after adding it from mutt.

I see the edit screen, but it doesn't respond to anything - it will only let met ^C out of it.
In that case the contact is saved, but I'd like to edit the name.

**Comment by untitaker** [comment]
Could you record a video/asciinema? Sorry, I dont know what you mean

On 30 May 2018 10:36:55 GMT+02:00, Ruben Verweij <notifications@github.com> wrote:
>Thank you very much for writing mates!
>
>I was wondering how to edit a contact after adding it from mutt.
>
>I see the edit screen, but it doesn't respond to anything - it will
>only let met ^C out of it.
>In that case the contact is saved, but I'd like to edit the name.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/mates.rs/issues/26

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rbnvrw** [comment]
Excuse me for the late reply. I've attached a screenshot of the screen I'm seeing (but I masked the name and email address). I get this screen after toggling the macro from mutt:
``
macro index,pager A \
    "<pipe-message>mates add | xargs mates edit<enter>" \
    "add the sender address"
``

I've tried pressing character keys / tab key / space key / enter key but nothing happens.
I can only press ^C and then it exits and the contact is stored.

**Comment by untitaker** [comment]
Xargs rarely works with interactive programs. I'd imagine spawning vim at the same location wouldn't end well either.

There are some wrapper scripts which fix stdin but I can't remember the name 

On May 31, 2018 9:59:08 PM GMT+02:00, Ruben Verweij <notifications@github.com> wrote:
>Excuse me for the late reply. I've attached a screenshot of the screen
>I'm seeing (but I masked the name and email address). I get this screen
>after toggling the macro from mutt:
>``
>macro index,pager A \
>    "<pipe-message>mates add | xargs mates edit<enter>" \
>    "add the sender address"
>``
>
>I've tried pressing character keys / tab key / space key / enter key
>but nothing happens.
>I can only press ^C and then it exits and the contact is stored.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/mates.rs/issues/26#issuecomment-393660927

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rbnvrw** [comment]
Thanks for the reply. However, on your own integration page (README) you list this exact same command to integrate mates.rs with mutt.
Can you please give a suggestion how to do it better and change it in your README?

**Comment by untitaker** [comment]
Oh, I will have a look then. 

On June 7, 2018 10:31:06 AM GMT+02:00, Ruben Verweij <notifications@github.com> wrote:
>Thanks for the reply. However, on your own integration page (README)
>you list this exact same command to integrate mates.rs with mutt.
>Can you please give a suggestion how to do it better and change it in
>your README?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/mates.rs/issues/26#issuecomment-395338087

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
I fixed it in the README! Turns out I forgot to push the working version to my dotfiles.

**Comment by rbnvrw** [comment]
Thank you, I can confirm it's working now!
